### ISSUE TITLE
Events keep firing

### ISSUE THREAD

**Issue by tonybyng** [nfragkos/statamic-eloquenty#3]
Hi

Im testing this out to see if it might be a fit for a job - I know its beta but you also said you wanted testers ;-) 

Im using an event listener to listen for the statamic entry saved event so that I can store some additional information on the record. It then does a saveQuietly so that it doesnt trigger another event and go into a loop. That was working on normal Statamic but within eloquenty it keeps going into the event and so loops forever.

```
    public function handle($event)
    {
          $entry = $event->entry;
          if ($entry->collectionHandle() === "products"){
              if ($entry->get("title")){
                  Log::info("got title - can update");
                   // update info on $entry such as .... 
                   $entry->set("categories",$categories);
                   $entry->mask = $myProductObject->getMask();
                   $entry->saveQuietly();
             }
         }
   } 
```

However now each time it saves Quietly its not as quiet and triggers another event which comes back into the same code and does the same thing over and over again

Any thoughts ?

Tony

**Comment by nfragkos** [comment]
Hi thank you very much for testing this. I have released v0.9 beta 9 with support for saving quietly: https://github.com/nfragkos/statamic-eloquenty/releases/tag/v0.9-beta.9

Update with composer as usually and please let me know if this fixes the problem.

**Comment by tonybyng** [comment]
@nfragkos Hi. I think it worked although after testing I then realised I needed to extend the eloquenty_entries table to store some additional fields (effectively copies of some of the data within the data json) so that i can create additional indices to find the data records i'm looking for quicker. I could create another model and link by the slug and then  run some queries via that other model but it seems a shame to do that.

Ive added the additional fields to the table but when i store the value it goes into the json data rather than the field on the table (I should say I am only using eloquenty for a single table so having extra fields on the record is of no consequence

Thanks

Tony

**Comment by tonybyng** [comment]
@nfragkos Ive rewritten my import routine so that its similar in function to your ImportEntries.php but whereas your ImportEntries is pulling data in from the existing text file entries, mine is importing from a csv file so I am either creating a new EntryModel or finding the existing EntryModel and updating it, so Ive now got the additional fields being stored on the model but when I create a new EntryModel and I want to save it without firing the listeners, the saveQuietly reports an error that the id  is empty, whereas the save() method correctly assigns the id. 

Im guessing there is a listener set up to allocate the id on save and so a saveQuietly doesnt work for a brand new record because not only is it not calling my listeners, its also not calling yours, however other than that, yes the saveQuietly seems to work thanks.

The only thing Im trying to figure now is that Im doing the EntryModel insertion in my import script but when I go to /cp and choose the products collection in Eloquenty I get a "Server Error" Statamic error in the bottom left corner and when I check the log it says

 Call to a member function absoluteUrl() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function absoluteUrl() on null at /var/www/html/vendor/statamic/cms/src/Routing/Routable.php:59)

**Comment by nfragkos** [comment]
Hi @tonybyng, unfortunately adding more columns to the table is not supported (just like in the original driver https://github.com/statamic/eloquent-driver). You should always query and filter data following the Statamic way. The Facade and antler tag I'm providing are extending the original classes so there's no need for custom queries on the model.

Indeed when creating new entries the id is null and that's normal for EntrySaving event. EntryCreated event should have the id though. 

Since saveQuietly() works fine now I'm closing the issue. Thanks again for testing and reporting this.
