### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by tonybyng** [nfragkos/statamic-eloquenty#4]
Hi

Nearly there. ;-) Got a file of 55,000 records imported and can search and get results up fine. The issue ive got is that when I go to the detail page so it goes to /path/slug Im getting 404 File not found. Ive probably missed a step somewhere but my understanding is that statamic identifies the slug in the path and then routes you to the view page and preloads the entry and Im guessing that it is looking for a text file and not finding one?

Can you reproduce that on your system ?

Thanks

Tony

**Comment by nfragkos** [comment]
Hi, I am using in on production (https://www.m4markets.com/about/news) for months now and its working fine. Did you set a route on the collection as stated here https://statamic.dev/collections#routing ?

**Comment by tonybyng** [comment]
Hi

It was all working  pre eloquenty but I've resolved the issue now.  Great tool. Will let you know if I hit any other issues but will close this down now.  Thanks again.

Tony
