### ISSUE TITLE
Middleware issue following upgrade

### ISSUE THREAD

**Issue by tonybyng** [nfragkos/statamic-eloquenty#5]
Hi

Just updated to your beta release 10 and applied the other statamic updates too and now getting

[2021-07-25 16:03:16] local.ERROR: Undefined array key 1 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /var/www/html/vendor/nfragkos/eloquenty/src/Http/Middleware/EloquentyMiddleware.php:29)

Which is the json_decode line here

```
            preg_match('/:initial-rows="(.*)"/', $response->getContent(), $matches, PREG_UNMATCHED_AS_NULL);
            $json = json_decode(html_entity_decode($matches[1]));
```

I ran a cache:clear after just in case but that didn't solve it

Any thoughts ?

Thanks

Tony

**Comment by tonybyng** [comment]
In fact. I've solved the problem but you might want to tweak those lines

It seems there was a yaml file issue somewhere - not one that ive edited so not sure if Statamic didnt save it properly but consequently that produced an error 500 and your middleware code assumes its going to get a "good" response from $response->getContent() and with a bad response, the code couldnt find the preg_match it was looking for so $matches was empty and so the error reported a problem in your middleware for $matches[1] being invalid when in fact it was as a result of an issue elsewhere

Anyway after you've read this you can close it but you might want to do a defensive check before referring to $matches[1]

Hope that helps

Tony

**Comment by nfragkos** [comment]
Hello, thank you for testing this. Unfortunately if there's an yaml parse error the middleware shows up first in the exception stack trace.

There is a check though and the json decode only runs on statamic.cp.collections.index route. Due to the flag PREG_UNMATCHED_AS_NULL $matches[1] will be set as null.

Thanks again, closing the issue...
